[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32dev
framework = arduino
upload_port = /dev/ttyUSB0
board_build.filesystem = spiffs

lib_deps = 
    adafruit/Adafruit SSD1306 @ ^2.5.9
    adafruit/Adafruit GFX Library @ ^1.11.9
    https://github.com/pschatzmann/ESP32-A2DP.git
    https://github.com/pschatzmann/arduino-audio-tools.git
    esphome/ESP32-audioI2S@^2.3.0
    


build_flags = -DCORE_DEBUG_LEVEL=5
monitor_speed = 115200
board_build.partitions = huge_app.csv

